#!/bin/sh /etc/rc.common
# Copyright (C) 2022 Wireless-Road

START=19
STOP=21

USE_PROCD=1
NAME=gs
PROG=/usr/bin/gs

SD="/dev/mmcblk0p1"
TGT="/mnt/gs"
TGT_DIR="/mnt/gs/1"

init_ads1115() {
    echo 860 > /sys/bus/iio/devices/iio\:device0/in_voltage0_sampling_frequency
    echo 860 > /sys/bus/iio/devices/iio\:device0/in_voltage1_sampling_frequency
}

init_selfcheck_file() {
	if [ ! -e "/tmp/gs_selfcheck" ]; then
		echo "self check file created"
		echo 0 > /tmp/gs_selfcheck
	fi
	if [ ! -e "/tmp/gs_in_4_20_channel0" ]; then
		echo "gs in 4-20 0  created"
		echo 0 > /tmp/gs_in_4_20_channel0
	fi
	if [ ! -e "/tmp/gs_in_4_20_channel1" ]; then
		echo "gs in 4-20 1 created"
		echo 0 > /tmp/gs_in_4_20_channel1
	fi

}

init_storage() {
    echo -n "Mounting SD..."
    if [ -d ${TGT_DIR} ]; then
	echo "Already mounted"
	return 0
    fi
    if [ -b "/dev/mmcblk0p1" ]; then
        mkdir -p ${TGT}
	fsck.fat -a ${SD}
        mount -t vfat ${SD} ${TGT}
        [ "$?" -eq 0 ] && {
            echo "OK"
            check_config
        }|| {
            echo "FAIL"
            return 1
        }
    else
        echo "SD Card not found"
        return 1
    fi
}
deinit_storage() {
    echo -n "Syncing and unmounting..."
    sync
    sleep 1
    umount ${TGT}
    [ "$?" -eq 0 ] && echo "OK" || {
        echo "FAIL"
        return 1
    }
}

check_config() {
    echo "Cheking config files..."
    for inst in "1" "2"; do
        mkdir -p "${TGT}"/"${inst}"
        dir="/etc/gs/"${inst}""
        for file in "${dir}"/* ; do
            cfg_f="${TGT}"/"${inst}"/$(basename "${file}")
            echo -n "$cfg_f"...
            [ -f "${cfg_f}" ] && {
                echo "OK"
            } || {
                cp "$file" "$TGT"/"$inst"
                echo "Restored"
            }
        done
    done
}

run_gs() {
    procd_open_instance
	procd_set_param command $PROG
#	procd_set_param respawn 3600 8 0
	procd_set_param respawn
#	uncomment following to catch app crashes
	procd_set_param limits core="unlimited"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
stop_gs() {
    :
}
start_service() {
	init_selfcheck_file
	init_ads1115
    init_storage
    run_gs
}

stop_service() {
    stop_gs
#    deinit_storage
}
