#!/bin/sh /etc/rc.common
# Copyright (C) 2023 Wireless-Road

START=13
STOP=21

USE_PROCD=1
NAME=mdmmon
PROG=/usr/bin/mdmmon

power_on_modem(){
    echo 8 > /sys/class/gpio/export
    echo out > /sys/class/gpio/gpio8/direction
    echo 1 > /sys/class/gpio/gpio8/value
}

start_monitor(){
    procd_open_instance
	procd_set_param command $PROG
    procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

start_service(){
    power_on_modem
    start_monitor
}
